dbt-databricks:
  outputs:
    dev:
      host: dbc-48574393-759b.cloud.databricks.com
      http_path: sql/protocolv1/o/4119582262816558/0322-165237-tr8dc9of
      schema: dbt
      threads: 1
      token: dapie81dea68b4914166af801cb72a230068 
      type: databricks
  target: dev
